### ISSUE TITLE
user.updatePrefixes is not a function

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwibnc#70]
~~~
worker_1    | 2020-06-24T11:44:44.645Z [worker] l_error TypeError: user.updatePrefixes is not a function
worker_1    |     at parsedModes.forEach (/kiwibnc/kiwibnc/src/worker/upstreamcommands.js:571:18)
worker_1    |     at Array.forEach (<anonymous>)
worker_1    |     at Object.commands.MODE (/kiwibnc/kiwibnc/src/worker/upstreamcommands.js:556:17)
worker_1    |     at Object.run (/kiwibnc/kiwibnc/src/worker/upstreamcommands.js:14:42)
worker_1    |     at process._tickCallback (internal/process/next_tick.js:68:7)
~~~

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwibnc/commit/8fedc402bc2e729439d8e742971a3804711b1081
